name: data_science_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=2.0.2
  - pandas=2.3.3
  - matplotlib=3.9.4
  - pillow=11.3.0
  - jupyter
  - ipykernel
  - pip
  - pip:
    - asttokens==3.0.0
    - comm==0.2.3
    - contourpy==1.3.0
    - cycler==0.12.1
    - debugpy==1.8.17
    - decorator==5.2.1
    - exceptiongroup==1.3.0
    - executing==2.2.1
    - fonttools==4.60.1
    - importlib_metadata==8.7.0
    - importlib_resources==6.5.2
    - ipython==8.18.1
    - jedi==0.19.2
    - jupyter_client==8.6.3
    - jupyter_core==5.8.1
    - kiwisolver==1.4.7
    - matplotlib-inline==0.1.7
    - nest-asyncio==1.6.0
    - packaging==25.0
    - parso==0.8.5
    - pexpect==4.9.0
    - platformdirs==4.4.0
    - prompt_toolkit==3.0.52
    - psutil==7.1.1
    - ptyprocess==0.7.0
    - pure_eval==0.2.3
    - pygments==2.19.2
    - pyparsing==3.2.5
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - pyzmq==27.1.0
    - stack-data==0.6.3
    - tornado==6.5.2
    - traitlets==5.14.3
    - typing_extensions==4.15.0
    - tzdata==2025.2
    - wcwidth==0.2.14
    - zipp==3.23.0
